### ISSUE TITLE
Breadcrumbs can be inaccurate

### ISSUE THREAD

**Issue by johnpennypacker** [uriweb/uri-modern#174]
## Issue Type

[X] Bug  
[] New Feature  
[] Enhancement  
    
## Description

On some posts, the breadcrumbs do not render properly.  e.g. on this site:

https://web.uri.edu/steep/save-the-date-fluoros-symposium-set-for-october-2020/

STEEP should be linked, and there should be another element in the trail that includes the current page title.

**Comment by bjcfuller** [comment]
I wonder if this is because of the way the permalink structure is set up, and because the post has belongs to multiple categories.

**Comment by bjcfuller** [comment]
@johnpennypacker The issue seems to be with the `get_page_by_path()` function in [`get-breadcrumbs.php#L71`](https://github.com/uriweb/uri-modern/blob/fbf9bf1451ae5f35df3fe12c4f6f3bac9fa8b8f3/inc/get-breadcrumbs.php#L71).  It returns null for posts, so the crumb for the page doesn't get built.  I don't know if there's an equivalent function for posts or not.

**Comment by johnpennypacker** [comment]
I wonder if updating 

$p = get_page_by_path( $path ); 

to 

$p = get_page_by_path( $path, OBJECT, array( ‘page’, ’post’ ) );

would fix it.

Looks like ‘page’ is the default, so it ignores posts.

https://developer.wordpress.org/reference/functions/get_page_by_path/

--

John Pennypacker
401.874.4890

I will be out of the office January 8 - 13

**Comment by bjcfuller** [comment]
I noticed that but it didn’t work.  I updated my comment in GitHub, sorry I probably should have made a new comment so you’d be notified.  Anyway, I found a solution.

**Comment by bjcfuller** [comment]
@johnpennypacker see https://github.com/uriweb/uri-modern/commit/7c84c286c346372d5396406d5533ed612224ef0f
